### ISSUE TITLE
windows error: ModuleNotFoundError: No module named 'webcolors'

### ISSUE THREAD

**Issue by baldonazionale** [magic-quill/MagicQuill#10]
what did I do wrong?

**Comment by zliucz** [comment]
Hi, there. Please follow the [setup guide](https://github.com/magic-quill/MagicQuill?tab=readme-ov-file#setup).

I think in your case, you might miss this step: `pip install -r requirements.txt` 

Hope this helps :)

**Comment by baldonazionale** [comment]
this is the guide I followed... and already did the " the pip install -r requirements.txt "

**Comment by baldonazionale** [comment]
also this command is not working on windows:
CUDA_VISIBLE_DEVICES=0 python gradio_run.py

while this one works (obviously)
python gradio_run.py

**Comment by zliucz** [comment]
Oh... It seems like you're having issues with CUDA commands, and based on the error, you might not have a GPU with CUDA support available on your system.

Since MagicQuill requires substantial GPU resources (approximately 15GB VRAM for editing operations), I suggest you try our [Huggingface Demo](https://huggingface.co/spaces/AI4Editing/MagicQuill) or [Web Demo (Alipay Cloud)](http://magic.chenjunfeng.xyz/).

**Comment by baldonazionale** [comment]
I should have a GPU, nevermind. thanks

**Comment by baldonazionale** [comment]
thanks
