### ISSUE TITLE
 size

### ISSUE THREAD

**Issue by ivanoff13** [magic-quill/MagicQuill#20]
how do I save an image with the original size?

**Comment by zliucz** [comment]
Hi! Currently, our system automatically resizes images to 512 pixels on the shorter side to optimize model performance, which inevitably reduces the resolution of high-quality images. You may manually resize the edited image, or try some super-resolution method to upscale the image. Thanks.

**Comment by Patagon-ui** [comment]
Thats littlebit sad, I've been buried in the codes for a whole day, trying to find out why I can't save output size in the original, I was starting to think the problem was me. so is it because these models are SD1.5? or is it a general limitation? and im wondering will this situation change in the future?

**Comment by zliucz** [comment]
@Patagon-ui Hi, check [issues#36](https://github.com/magic-quill/MagicQuill/issues/36). Thanks.

**Comment by Patagon-ui** [comment]
Oh thanks for the feedback @zliucz this works fine for me.
