### ISSUE TITLE
Flux coming?

### ISSUE THREAD

**Issue by motowntalent** [magic-quill/MagicQuill#7]
Any plans to add Flux as a model to use? I know the SD1.5 is less resource intensive, but it would be nice to have the option.

**Comment by zliucz** [comment]
Hi! Thank you for your interest. Currently, we don't have immediate plans to add Flux model support.

This is mainly because the associated Control and Inpainting modules for Flux are not yet as mature as we'd like them to be. 

But we'll keep monitoring Flux's development, and might consider adding support in the future when these features become more complete. Thanks for your suggestion!
